name: CI / Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-services:
    name: Test ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - services/auth

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "${{ matrix.service }}/uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.service }}/pyproject.toml"

      - name: Run Pytest
        run: |
          cd ${{ matrix.service }}
          uv sync
          uv run pytest